In [1]:
#Importation des données
import pandas as pd

achat = pd.read_csv("Achat.csv")
loc = pd.read_csv("LocationParMois.csv")
prix_loc = pd.read_csv("PrixLocationSurDemande.csv")
prix_dem = pd.read_csv("PrixSurDemande.csv")

# Nombre de références uniques
print("Achat :", achat["Réf. client :"].nunique())
print("Location :", loc["Réf. client :"].nunique())
print("Prix location sur demande :", prix_loc["Réf. client :"].nunique())
print("Prix sur demande :", prix_dem["Réf. client :"].nunique())

# Vérification que toutes les références sont dans la base principale
set_achat = set(achat["Réf. client :"])
set_loc = set(loc["Réf. client :"])
set_prix_dem = set(prix_dem["Réf. client :"])
set_prix_loc = set(prix_loc["Réf. client :"])

print("Achat ⊂ PrixLocationSurDemande :", set_achat.issubset(set_prix_loc))
print("Location ⊂ PrixLocationSurDemande :", set_loc.issubset(set_prix_loc))
print("PrixSurDemande ⊂ PrixLocationSurDemande :", set_prix_dem.issubset(set_prix_loc))

Achat : 6495
Location : 140
Prix location sur demande : 36
Prix sur demande : 1430
Achat ⊂ PrixLocationSurDemande : False
Location ⊂ PrixLocationSurDemande : False
PrixSurDemande ⊂ PrixLocationSurDemande : False

Nettoyage de chaque base de données

Objectif de nettoyage de Achat.csv
Dans cette table, nous devons convertir le kilométrage en entier,la date de 1ère immatriculation en format datetime et le prix en numérique. 
Ensuite enlever les km, les espaces, extraire les valeurs numériques pour le poids à vide, nettoyer les valeurs incohérentes.
Enfin supprimer les doublons sur le ref.client.

In [3]:

import numpy as np
# Copie de la base pour la nettoyer 
achat_clean = achat.copy()

# Nettoyage du kilométrage 
def clean_km(x):
    if isinstance(x, str):
        return int(x.replace(" km", "").replace(" ", "").replace(",", ""))
    return np.nan

achat_clean["Kilométrage"] = achat_clean["Kilométrage"].apply(clean_km)

# Nettoyage des dates
achat_clean["Date de 1ere immatriculation"] = pd.to_datetime(
    achat_clean["Date de 1ere immatriculation"], errors="coerce", dayfirst=True
)

# Nettoyage du prix 
achat_clean["Prix"] = pd.to_numeric(achat_clean["Prix"], errors="coerce")

# Nettoyage du poids 
def clean_weight(x):
    if isinstance(x, str):
        return float(x.replace(" Tonnes", "").replace(",", "."))
    return np.nan

achat_clean["Poids à vide"] = achat_clean["Poids à vide"].apply(clean_weight)
achat_clean["PTC"] = achat_clean["PTC"].apply(clean_weight)

# Nettoyage des colonnes texte 
colonnes_texte = ["Description", "Energie", "Marque", "Modèle", "Pays", 
                  "Vendeur", "Localisation", "Etat"]

for col in colonnes_texte:
    achat_clean[col] = achat_clean[col].astype(str).str.strip()

# Suppression des doublons 
achat_clean.drop_duplicates(subset=["Réf. client :"], inplace=True)

# Suppression de la colonne Photo
if "Photo" in achat_clean.columns:
    achat_clean.drop(columns=["Photo"], inplace=True)


# Export de la table propre
achat_clean.to_csv("Achat_clean.csv", index=False)

achat_clean.head()

,Réf. client :,Description,Kilométrage,Date de 1ere immatriculation,Energie,Marque,Modèle,Pays,Prix,Vendeur,Localisation,Poids à vide,PTC,Essieux,Puissance,Etat
0,00013489,Tracteur DAF XF 530,538000.0,2019-12-18,Gazoil,DAF,530,FRANCE,45800.0,BERROYER,Vendée,8.27,19.0,4x2,530.0,Occasion
1,LOC-VO24-1637-A,Tracteur Volvo neuf FH 500 AERO Globetrotter X...,3000.0,2025-09-25,Gazoil,Volvo,530,FRANCE,2600.0,SYLTRAILER,PyrénéesOrientales,8.27,19.0,4x2,510.0,Neuf
2,LOC-VO24-1637-C,Tracteur Volvo FH 500 AERO Globetrotter XXL (L...,3000.0,2025-09-25,Gazoil,Volvo,1843,FRANCE,2600.0,SYLTRAILER,PyrénéesOrientales,8.27,19.0,4x2,510.0,Occasion
3,GK-715-RN,Tracteur auto-école Iveco S-WAY 460,70400.0,2022-11-23,Gazoil,Iveco,440,FRANCE,65000.0,Mauffrey,Vosges,7.51,19.0,4x2,430.0,Occasion
4,FZ-374-MW,Tracteur auto-école Iveco S-WAY 460,85555.0,2021-05-27,Gazoil,Iveco,1848 LS,FRANCE,62000.0,Mauffrey,Vosges,8.27,44.0,4x2,482.0,Occasion

Objectif de nettoyage de LocationParMois:
Le nettoyage de la table LocationParMois.csv vise à rendre les données cohérentes, exploitables et prêtes pour l’analyse marketing. Cette base contient des informations hétérogènes sur les véhicules en location, avec des formats parfois irréguliers (kilométrage en texte, dates non standardisées, poids exprimés en chaînes, espaces parasites dans les colonnes texte, etc.). L’objectif du nettoyage est donc d’harmoniser les types de données, de corriger les incohérences, de supprimer les colonnes inutiles comme Photo, et d’éliminer les doublons afin d’obtenir une version fiable et structurée de la table. Cette étape est indispensable pour garantir une fusion correcte avec les autres bases et permettre des analyses précises dans les futurs dashboards.

In [4]:
# Copie de la base pour la nettoyer 
location_clean = loc.copy()

# Nettoyage du kilométrage 
def clean_km(x):
    if isinstance(x, str):
        return int(x.replace(" km", "").replace(" ", "").replace(",", ""))
    return np.nan

location_clean["Kilométrage"] = location_clean["Kilométrage"].apply(clean_km)

# Nettoyage des dates
location_clean["Date de 1ere immatriculation"] = pd.to_datetime(
    location_clean["Date de 1ere immatriculation"], errors="coerce", dayfirst=True
)

# Nettoyage du prix
location_clean["Prix"] = pd.to_numeric(location_clean["Prix"], errors="coerce")

# Nettoyage du poids 
def clean_weight(x):
    if isinstance(x, str):
        return float(x.replace(" Tonnes", "").replace(",", "."))
    return np.nan

location_clean["Poids à vide"] = location_clean["Poids à vide"].apply(clean_weight)
location_clean["PTC"] = location_clean["PTC"].apply(clean_weight)

# Nettoyage des colonnes texte 
colonnes_texte = ["Description", "Energie", "Marque", "Modèle", "Pays", 
                  "Vendeur", "Localisation", "Etat"]

for col in colonnes_texte:
    location_clean[col] = location_clean[col].astype(str).str.strip()

# Suppression de la colonne Photo
if "Photo" in location_clean.columns:
    location_clean.drop(columns=["Photo"], inplace=True)

# Suppression des doublons
location_clean.drop_duplicates(subset=["Réf. client :"], inplace=True)

# Export de la table propre
location_clean.to_csv("Location_clean.csv", index=False)

location_clean.head()

,Réf. client :,Description,Kilométrage,Date de 1ere immatriculation,Energie,Marque,Modèle,Pays,Prix,Vendeur,Localisation,Poids à vide,PTC,Essieux,Puissance,Etat
0,LOC-VO24-1338,Tracteur Volvo F6 FH 460 Hydraulique (Location...,580000.0,2019-04-04,Gazoil,Volvo,440,FRANCE,1900,SYLTRAILER,PyrénéesOrientales,7.65,19.0,4x2,460.0,Occasion
1,VO24-1338,Tracteur Volvo F6 FH 460 Hydraulique (Location...,580000.0,2019-04-04,Hybride,Volvo,18.470,FRANCE,1900,SYLTRAILER,PyrénéesOrientales,7.65,19.0,4x2,460.0,Occasion
2,LOC-VO24-1339,Tracteur Volvo F6 FH 460 Hydraulique (Location...,580000.0,2019-04-04,Gazoil,Volvo,480,FRANCE,1900,SYLTRAILER,PyrénéesOrientales,10.91,19.0,4x2,460.0,Occasion
3,7CB290EA-4ECA-4402-ADF8-07C45613EB6A,Tracteur produits dangereux / adr Renault T-Se...,455375.0,2020-01-16,Gazoil,Renault,480,FRANCE,754,RENAULT TRUCKS GRAND PARIS MASSY,Essonne,8.00,19.0,4x2,500.0,Occasion
4,169-GF909GX,Tracteur Mercedes Actros 1848,673345.0,2022-06-17,Gazoil,Mercedes,530,FRANCE,1900,INTER LOC 85,Vendée,7.64,19.0,4x2,470.0,Occasion

Objectif de nettoyage de la table PrixLocationSurDemande:
La table PrixLocationSurDemande.csv regroupe des véhicules proposés à la location dont le tarif n’est pas affiché. Elle présente donc des particularités qui nécessitent un nettoyage rigoureux avant toute fusion avec les autres bases. L’objectif du nettoyage est d’harmoniser les formats (kilométrage, dates, poids), de normaliser les colonnes textuelles, de supprimer les informations inutiles comme les URLs de photos, et de gérer correctement l’absence de prix en créant une structure cohérente pour les analyses futures. Cette étape garantit que les véhicules “sur demande” pourront être intégrés proprement dans la base finale, sans créer d’incohérences ou de ruptures dans les dashboards marketing.

In [5]:
# Copier de la base pour le nettoyage
prix_loc_demande_clean = prix_loc.copy()

# Nettoyage du kilométrage 
def clean_km(x):
    if isinstance(x, str):
        return int(x.replace(" km", "").replace(" ", "").replace(",", ""))
    return np.nan

prix_loc_demande_clean["Kilométrage"] = prix_loc_demande_clean["Kilométrage"].apply(clean_km)

# Nettoyage des dates
prix_loc_demande_clean["Date de 1ere immatriculation"] = pd.to_datetime(
    prix_loc_demande_clean["Date de 1ere immatriculation"], errors="coerce", dayfirst=True
)

# Prix : toujours "Tarif de location sur demande" → NaN 
prix_loc_demande_clean["Prix"] = np.nan

#Colonne indiquant si le prix est connu
prix_loc_demande_clean["Prix_connu"] = False


# Nettoyage du poids 
def clean_weight(x):
    if isinstance(x, str):
        return float(x.replace(" Tonnes", "").replace(",", "."))
    return np.nan

prix_loc_demande_clean["Poids à vide"] = prix_loc_demande_clean["Poids à vide"].apply(clean_weight)
prix_loc_demande_clean["PTC"] = prix_loc_demande_clean["PTC"].apply(clean_weight)

# Nettoyage des colonnes texte
colonnes_texte = ["Description", "Energie", "Marque", "Modèle", "Pays", 
                  "Vendeur", "Localisation", "Etat"]

for col in colonnes_texte:
    prix_loc_demande_clean[col] = prix_loc_demande_clean[col].astype(str).str.strip()

# Suppression de la colonne Photo 
if "Photo" in prix_loc_demande_clean.columns:
    prix_loc_demande_clean.drop(columns=["Photo"], inplace=True)

# Suppression des doublons 
prix_loc_demande_clean.drop_duplicates(subset=["Réf. client :"], inplace=True)

# Export de la table propre 
prix_loc_demande_clean.to_csv("PrixLocationSurDemande_clean.csv", index=False)

prix_loc_demande_clean.head()

,Réf. client :,Description,Kilométrage,Date de 1ere immatriculation,Energie,Marque,Modèle,Pays,Prix,Vendeur,Localisation,Poids à vide,PTC,Essieux,Puissance,Etat,Prix_connu
0,VO24-1335,Tracteur Volvo F6 FH 460 Hydraulique (LOA LOCA...,637883.0,2019-04-02,Gazoil,Volvo,2046,FRANCE,NaN,SYLTRAILER,PyrénéesOrientales,7.65,19.0,4x2,460.0,Occasion,False
1,VO24-1338,Tracteur Volvo F6 FH 460 Hydraulique (LOA LOCA...,666959.0,2019-04-04,Gazoil,Volvo,500 Globetrotter,FRANCE,NaN,SYLTRAILER,PyrénéesOrientales,7.65,19.0,4x2,460.0,Occasion,False
2,VO24-1346,Tracteur Volvo F6 460 (LOA LOCATION OPTION D'A...,455619.0,2017-10-03,Gazoil,Volvo,460 FTP,FRANCE,NaN,SYLTRAILER,PyrénéesOrientales,7.80,19.0,4x2,460.0,Occasion,False
3,VO24-1334,Tracteur Volvo F6 FH 460 Hydraulique (LOA LOCA...,629709.0,2019-04-02,Hybride,Volvo,520,FRANCE,NaN,SYLTRAILER,PyrénéesOrientales,7.65,19.0,4x2,460.0,Occasion,False
4,VO24-1339,Tracteur Volvo F6 FH 460 Hydraulique (LOA LOCA...,584503.0,2019-06-13,Gazoil,Volvo,460,FRANCE,NaN,SYLTRAILER,PyrénéesOrientales,7.65,19.0,4x2,460.0,Occasion,False

Objectif de nettoyage de la table PrisSurDemande:
La table PrixSurDemande regroupe les véhicules proposés à la vente dont le prix n’est pas affiché. Comme pour les autres bases “sur demande”, plusieurs colonnes présentent des formats irréguliers : kilométrage exprimé en texte, dates non standardisées, poids indiqués sous forme de chaînes, ou encore des variations dans les colonnes textuelles. L’objectif du nettoyage est donc d’harmoniser les types de données, de normaliser les valeurs textuelles, de supprimer les colonnes inutiles comme Photo, et de gérer correctement l’absence de prix en remplaçant les valeurs textuelles par des valeurs manquantes (NaN). Ce nettoyage garantit que cette base pourra être fusionnée proprement avec les autres tables et intégrée dans les analyses marketing sans créer d’incohérences.

In [6]:
#Copie de la base pour le nettoyage
prix_demande_clean = prix_dem.copy()

#Nettoyage du kilométrage
def clean_km(x):
    if isinstance(x, str):
        return int(x.replace(" km", "").replace(" ", "").replace(",", ""))
    return np.nan

prix_demande_clean["Kilométrage"] = prix_demande_clean["Kilométrage"].apply(clean_km)

#Nettoyage des dates
prix_demande_clean["Date de 1ere immatriculation"] = pd.to_datetime(
    prix_demande_clean["Date de 1ere immatriculation"], errors="coerce", dayfirst=True
)

#Prix : toujours "Prix sur demande" → NaN 
prix_demande_clean["Prix"] = np.nan

#Colonne indiquant si le prix est connu
prix_demande_clean["Prix_connu"] = False

#Nettoyage du poids
def clean_weight(x):
    if isinstance(x, str):
        return float(x.replace(" Tonnes", "").replace(",", "."))
    return np.nan

prix_demande_clean["Poids à vide"] = prix_demande_clean["Poids à vide"].apply(clean_weight)
prix_demande_clean["PTC"] = prix_demande_clean["PTC"].apply(clean_weight)

#Nettoyage des colonnes texte
colonnes_texte = ["Description", "Energie", "Marque", "Modèle", "Pays", 
                  "Vendeur", "Localisation", "Etat"]

for col in colonnes_texte:
    prix_demande_clean[col] = prix_demande_clean[col].astype(str).str.strip()

#Suppression de la colonne Photo
if "Photo" in prix_demande_clean.columns:
    prix_demande_clean.drop(columns=["Photo"], inplace=True)

#Suppression des doublons
prix_demande_clean.drop_duplicates(subset=["Réf. client :"], inplace=True)

#Export de la table propre
prix_demande_clean.to_csv("PrixSurDemande_clean.csv", index=False)

prix_demande_clean.head()

,Réf. client :,Description,Kilométrage,Date de 1ere immatriculation,Energie,Marque,Modèle,Pays,Prix,Vendeur,Localisation,Poids à vide,PTC,Essieux,Puissance,Etat,Prix_connu
0,00013161,Tracteur Mercedes Arocs 2046,220000.0,2018-01-31,Gazoil,Mercedes,2046,FRANCE,NaN,BERROYER,Vendée,7.51,19.0,4x2,460.0,Occasion,False
1,VO25-1966,Tracteur Volvo F6 460 FH,511000.0,2019-04-04,Gazoil,Volvo,1843,FRANCE,NaN,SYLTRAILER,PyrénéesOrientales,7.65,19.0,4x2,460.0,Occasion,False
2,VO26-2072,Tracteur Iveco S-WAY 490,416350.0,2022-10-21,Gazoil,Iveco,2046,FRANCE,NaN,SYLTRAILER,PyrénéesOrientales,6.87,18.0,4x2,490.0,Occasion,False
3,VO25-1984,Tracteur produits dangereux / adr Renault neuf...,74.0,2024-06-12,Gazoil,Renault,530,FRANCE,NaN,SYLTRAILER,PyrénéesOrientales,8.58,19.0,4x2,480.0,Neuf,False
4,VO25-1969,Tracteur Volvo F6 460 FH,668000.0,2019-11-15,Gazoil,Volvo,1843,FRANCE,NaN,SYLTRAILER,PyrénéesOrientales,7.64,19.0,4x2,460.0,Occasion,False